-- Dev/test catalog seed. Provides enough rows to exercise cursor pagination
-- (limit 20 -> multiple pages) and grid virtualization (rows >> viewport).
-- Idempotent via ON CONFLICT on slug.
INSERT INTO apps (slug, name, tagline, description, icon, category, status, sort_order)
VALUES
  ('insight-analytics', 'InsightAnalytics', 'Product analytics, simplified', 'Track funnels, retention, and user journeys across your products.', 'chart-line', 'Analytics', 'available', 10),
  ('flux-deploy', 'FluxDeploy', 'Ship with confidence', 'Continuous delivery pipelines with one-click rollbacks.', 'rocket', 'DevOps', 'available', 20),
  ('sentinel-logs', 'SentinelLogs', 'Logs you can actually read', 'Centralized, searchable logging with smart alerting.', 'scroll-text', 'Observability', 'available', 30),
  ('vault-secrets', 'VaultSecrets', 'Secrets, secured', 'Store and rotate credentials with fine-grained access control.', 'key-round', 'Security', 'available', 40),
  ('pulse-monitor', 'PulseMonitor', 'Always-on uptime checks', 'Monitor endpoints worldwide and get paged before users notice.', 'activity', 'Observability', 'available', 50),
  ('atlas-maps', 'AtlasMaps', 'Geospatial made easy', 'Render, query, and analyze location data at scale.', 'map', 'Data', 'available', 60),
  ('forge-ci', 'ForgeCI', 'Builds that fly', 'Parallelized CI runners with intelligent caching.', 'hammer', 'DevOps', 'available', 70),
  ('beacon-notify', 'BeaconNotify', 'Reach every channel', 'Unified notifications across email, SMS, push, and chat.', 'bell', 'Messaging', 'available', 80),
  ('cipher-scan', 'CipherScan', 'Catch vulnerabilities early', 'Static and dependency scanning baked into your workflow.', 'shield-check', 'Security', 'available', 90),
  ('ledger-pay', 'LedgerPay', 'Payments without the pain', 'Accept, reconcile, and report on payments globally.', 'credit-card', 'Finance', 'available', 100),
  ('quill-docs', 'QuillDocs', 'Docs that write themselves', 'Collaborative documentation with AI-assisted drafting.', 'file-pen', 'Productivity', 'available', 110),
  ('nimbus-store', 'NimbusStore', 'Object storage, unlimited', 'Durable, versioned object storage with a simple API.', 'cloud', 'Infrastructure', 'available', 120),
  ('relay-queue', 'RelayQueue', 'Messaging at scale', 'Durable queues and streams for event-driven systems.', 'list-ordered', 'Infrastructure', 'available', 130),
  ('prism-bi', 'PrismBI', 'Dashboards in minutes', 'Self-serve business intelligence for every team.', 'layout-dashboard', 'Analytics', 'available', 140),
  ('harbor-registry', 'HarborRegistry', 'Your private registry', 'Host and scan container images securely.', 'container', 'DevOps', 'available', 150),
  ('echo-support', 'EchoSupport', 'Delight your customers', 'Omnichannel helpdesk with AI triage.', 'headset', 'Support', 'available', 160),
  ('grove-crm', 'GroveCRM', 'Relationships that grow', 'A lightweight CRM that scales with your pipeline.', 'users', 'Sales', 'available', 170),
  ('tempo-schedule', 'TempoSchedule', 'Plan without the chaos', 'Smart scheduling and resource planning.', 'calendar-clock', 'Productivity', 'available', 180),
  ('lumen-search', 'LumenSearch', 'Search that understands', 'Semantic search-as-a-service for your data.', 'search', 'Data', 'available', 190),
  ('cobalt-auth', 'CobaltAuth', 'Auth, done right', 'Drop-in authentication and authorization.', 'lock', 'Security', 'available', 200),
  ('drift-flags', 'DriftFlags', 'Ship dark, release light', 'Feature flags and progressive delivery.', 'flag', 'DevOps', 'available', 210),
  ('mosaic-design', 'MosaicDesign', 'Design systems unified', 'Tokens, components, and docs in one place.', 'palette', 'Design', 'available', 220),
  ('orbit-iot', 'OrbitIoT', 'Connect every device', 'Manage fleets of devices with real-time telemetry.', 'radio', 'IoT', 'available', 230),
  ('cascade-etl', 'CascadeETL', 'Pipelines without plumbing', 'Build and orchestrate data pipelines visually.', 'workflow', 'Data', 'available', 240),
  ('summit-status', 'SummitStatus', 'Trust through transparency', 'Public status pages and incident comms.', 'gauge', 'Observability', 'available', 250),
  ('verdant-cost', 'VerdantCost', 'Cloud spend under control', 'Cost visibility and rightsizing recommendations.', 'piggy-bank', 'Finance', 'available', 260),
  ('signal-chat', 'SignalChat', 'Chat for builders', 'Embeddable real-time chat and presence.', 'message-circle', 'Messaging', 'available', 270),
  ('quartz-cache', 'QuartzCache', 'Speed, on demand', 'Managed in-memory caching at the edge.', 'zap', 'Infrastructure', 'available', 280),
  ('aurora-ml', 'AuroraML', 'Models in production', 'Train, deploy, and monitor ML models.', 'brain-circuit', 'AI', 'coming_soon', 290),
  ('helix-warehouse', 'HelixWarehouse', 'Analytics-ready data', 'A serverless data warehouse for fast queries.', 'database', 'Data', 'coming_soon', 300),
  ('nova-mail', 'NovaMail', 'Transactional email', 'Reliable transactional email with deliverability insights.', 'bell', 'Messaging', 'available', 310),
  ('spark-stream', 'SparkStream', 'Streams in real time', 'Process and route event streams with low latency.', 'activity', 'Data', 'available', 320),
  ('terra-form', 'TerraForm', 'Infrastructure as code', 'Plan and apply infrastructure changes safely.', 'workflow', 'Infrastructure', 'available', 330),
  ('onyx-backup', 'OnyxBackup', 'Backups you can trust', 'Automated, encrypted backups with point-in-time restore.', 'cloud', 'Infrastructure', 'available', 340),
  ('vertex-graph', 'VertexGraph', 'Connected data', 'A managed graph database for relationship-heavy data.', 'workflow', 'Data', 'available', 350),
  ('crest-forms', 'CrestForms', 'Forms that convert', 'Build and embed forms with validation and analytics.', 'file-pen', 'Productivity', 'available', 360),
  ('halo-identity', 'HaloIdentity', 'One identity everywhere', 'Single sign-on and directory sync.', 'lock', 'Security', 'available', 370),
  ('pixel-cdn', 'PixelCDN', 'Assets at the edge', 'Global content delivery with smart image optimization.', 'zap', 'Infrastructure', 'available', 380),
  ('cedar-tasks', 'CedarTasks', 'Work, organized', 'Task and project tracking for fast teams.', 'list-ordered', 'Productivity', 'available', 390),
  ('flint-search', 'FlintSearch', 'Instant site search', 'Add fast, typo-tolerant search to any product.', 'search', 'Data', 'available', 400),
  ('ember-alerts', 'EmberAlerts', 'On-call without burnout', 'Alerting and incident response that respects your time.', 'bell', 'Observability', 'available', 410),
  ('basalt-db', 'BasaltDB', 'Postgres, managed', 'Production Postgres with backups and replicas.', 'database', 'Infrastructure', 'available', 420),
  ('cove-storage', 'CoveStorage', 'Files made simple', 'Drop-in file storage with signed URLs.', 'cloud', 'Infrastructure', 'available', 430),
  ('arbor-billing', 'ArborBilling', 'Subscriptions, solved', 'Metered and seat-based billing with dunning.', 'credit-card', 'Finance', 'available', 440),
  ('lyric-feedback', 'LyricFeedback', 'Hear every user', 'Collect and triage product feedback.', 'message-circle', 'Support', 'available', 450),
  ('zephyr-jobs', 'ZephyrJobs', 'Background work, handled', 'Scalable job scheduling and queues.', 'workflow', 'Infrastructure', 'available', 460),
  ('saffron-crm', 'SaffronCRM', 'Pipeline at a glance', 'A sales CRM with forecasting and automation.', 'users', 'Sales', 'available', 470),
  ('cobalt-reports', 'CobaltReports', 'Reports on autopilot', 'Scheduled, shareable reports from any data source.', 'chart-line', 'Analytics', 'available', 480),
  ('marble-wiki', 'MarbleWiki', 'Knowledge that sticks', 'A fast internal wiki with powerful search.', 'file-pen', 'Productivity', 'available', 490),
  ('ridge-router', 'RidgeRouter', 'Smart API gateway', 'Routing, rate limits, and auth for your APIs.', 'workflow', 'Infrastructure', 'available', 500),
  ('aspen-audit', 'AspenAudit', 'Compliance, continuous', 'Audit logging and evidence collection.', 'shield-check', 'Security', 'available', 510),
  ('delta-sync', 'DeltaSync', 'Data, in sync', 'Reliable data sync between systems.', 'workflow', 'Data', 'available', 520),
  ('willow-chat', 'WillowChat', 'Support conversations', 'Live chat with bots and human handoff.', 'message-circle', 'Support', 'available', 530),
  ('comet-cron', 'CometCron', 'Scheduled, reliably', 'Cron jobs with retries and observability.', 'calendar-clock', 'Infrastructure', 'available', 540),
  ('granite-acl', 'GraniteACL', 'Permissions at scale', 'Fine-grained, relationship-based authorization.', 'lock', 'Security', 'available', 550),
  ('opal-insights', 'OpalInsights', 'Metrics that matter', 'Custom metrics, charts, and alerts.', 'gauge', 'Analytics', 'available', 560),
  ('birch-builder', 'BirchBuilder', 'Internal tools, fast', 'Build admin panels without the boilerplate.', 'layout-dashboard', 'Productivity', 'available', 570),
  ('slate-notes', 'SlateNotes', 'Notes for teams', 'Shared notes with rich text and mentions.', 'file-pen', 'Productivity', 'available', 580),
  ('zenith-edge', 'ZenithEdge', 'Compute at the edge', 'Run functions close to your users worldwide.', 'zap', 'Infrastructure', 'coming_soon', 590)
ON CONFLICT (slug) DO NOTHING;
